[2024-09-11T18:54:28.396+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-11T18:54:28.407+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: docker_operator_example.run_docker_container manual__2024-09-11T18:54:27.689092+00:00 [queued]>
[2024-09-11T18:54:28.410+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: docker_operator_example.run_docker_container manual__2024-09-11T18:54:27.689092+00:00 [queued]>
[2024-09-11T18:54:28.411+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-09-11T18:54:28.417+0000] {taskinstance.py:2888} INFO - Executing <Task(DockerOperator): run_docker_container> on 2024-09-11 18:54:27.689092+00:00
[2024-09-11T18:54:28.420+0000] {standard_task_runner.py:72} INFO - Started process 223 to run task
[2024-09-11T18:54:28.422+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'docker_operator_example', 'run_docker_container', 'manual__2024-09-11T18:54:27.689092+00:00', '--job-id', '282', '--raw', '--subdir', 'DAGS_FOLDER/my_dag.py', '--cfg-path', '/tmp/tmp8f3m6gbz']
[2024-09-11T18:54:28.424+0000] {standard_task_runner.py:105} INFO - Job 282: Subtask run_docker_container
[2024-09-11T18:54:28.450+0000] {task_command.py:467} INFO - Running <TaskInstance: docker_operator_example.run_docker_container manual__2024-09-11T18:54:27.689092+00:00 [running]> on host 8c7f0a0e6e80
[2024-09-11T18:54:28.503+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='docker_operator_example' AIRFLOW_CTX_TASK_ID='run_docker_container' AIRFLOW_CTX_EXECUTION_DATE='2024-09-11T18:54:27.689092+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-11T18:54:27.689092+00:00'
[2024-09-11T18:54:28.504+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-11T18:54:28.522+0000] {docker.py:367} INFO - Starting docker container from image python:3.8-slim
[2024-09-11T18:54:28.524+0000] {docker.py:375} WARNING - Using remote engine or docker-in-docker and mounting temporary volume from host is not supported. Falling back to `mount_tmp_dir=False` mode. You can set `mount_tmp_dir` parameter to False to disable mounting and remove the warning
[2024-09-11T18:54:28.753+0000] {docker.py:438} INFO - Hello from Docker!
[2024-09-11T18:54:28.873+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-11T18:54:28.873+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=docker_operator_example, task_id=run_docker_container, run_id=manual__2024-09-11T18:54:27.689092+00:00, execution_date=20240911T185427, start_date=20240911T185428, end_date=20240911T185428
[2024-09-11T18:54:28.914+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-09-11T18:54:28.925+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-11T18:54:28.927+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
